/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsRouteRouteImport } from './routes/auctions/route'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as AuctionsAuctionUuidRouteImport } from './routes/auctions/$auctionUuid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRouteRoute = AuctionsRouteRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuctionsRouteRoute,
} as any)
const AuctionsAuctionUuidRoute = AuctionsAuctionUuidRouteImport.update({
  id: '/$auctionUuid',
  path: '/$auctionUuid',
  getParentRoute: () => AuctionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRouteRouteWithChildren
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions/': typeof AuctionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions': typeof AuctionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRouteRouteWithChildren
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRoute
  '/auctions/': typeof AuctionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions' | '/auctions/$auctionUuid' | '/auctions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions/$auctionUuid' | '/auctions'
  id: '__root__' | '/' | '/auctions' | '/auctions/$auctionUuid' | '/auctions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRouteRoute: typeof AuctionsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof AuctionsRouteRoute
    }
    '/auctions/$auctionUuid': {
      id: '/auctions/$auctionUuid'
      path: '/$auctionUuid'
      fullPath: '/auctions/$auctionUuid'
      preLoaderRoute: typeof AuctionsAuctionUuidRouteImport
      parentRoute: typeof AuctionsRouteRoute
    }
  }
}

interface AuctionsRouteRouteChildren {
  AuctionsAuctionUuidRoute: typeof AuctionsAuctionUuidRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
}

const AuctionsRouteRouteChildren: AuctionsRouteRouteChildren = {
  AuctionsAuctionUuidRoute: AuctionsAuctionUuidRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
}

const AuctionsRouteRouteWithChildren = AuctionsRouteRoute._addFileChildren(
  AuctionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRouteRoute: AuctionsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
